### ISSUE TITLE
Delay (or wait) for the 'Analyzing URL' step

### ISSUE THREAD

**Issue by avantida** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#1]
First off: **THANK YOU** for this tool.
We had an issue with some malware on a wordpress site which basically polluted our google search.
So I used your tool to get rid of hundreds of links.

While doing so, I did notice that the Analyzing URL step can take longer than 1.3 sec, so the[ ` $("#gwt-uid-88").trigger('click');`](https://github.com/noitcudni/google-webmaster-tools-bulk-outdated-content-removal/blob/48b17823cc6f64a5e601a2f6538888d3d3a04bda/bulk_outdated_content_removal.js#L29) does not always work.

I had to get going removing the links first, so I did not further look into amending the code as I have no knowledge yet how to debug such an extension.
In a way I would put in something like (pseudo code)
```javascript
    var $requestRemovalConfirmbtn = null;
    do
    {
        setTimeout(() => {
            $requestRemovalConfirmbtn = $("#gwt-uid-88");
          }, 300);
    } while ($requestRemovalConfirmbtn == null || !$requestRemovalConfirmbtn .is(':visible'))
   $requestRemovalConfirmbtn.trigger('click');
```

I set the initial wait to only 300ms, in the hope it will even speed up the whole operation. A similar approach could then be taken for the `"#gwt-uid-96"` button too.

**Comment by noitcudni** [comment]
Got it. Thanks for bringing that up to my attention. I guess I do need to be more conservative and wait for the modal dialog to be visible. I will fix it soon.

**Comment by noitcudni** [comment]
@avantida Your code snippet won't work as expected. We can consider `setTimeout` as nonblocking.  Upon calling `setTimeout`, the interpreter will just execute the next operation. In your case, it's the stuff inside the while loop. Chances are that the button is not visible yet, so you'll set up another timeout. Over and over again. 

I have a fix for this. Please send me some sample outdated urls. Thanks.

**Comment by avantida** [comment]
Hi @noitcudni , yes upon re-reading that bit of pseudo code; 🤦‍♂️

Unfortunately I can not share the list of outdated urls, yet if you have any domain set up in the Google Search Console, you can generate any non existing (404) URL to that domain; like:
domain.com/AAAAA
domain.com/AAAAB
domain.com/AAAAC
etc...

**Comment by noitcudni** [comment]
ah..good call. Thanks. I will do that tonight.

**Comment by noitcudni** [comment]
Here's the commit
https://github.com/noitcudni/google-webmaster-tools-bulk-outdated-content-removal/commit/1538c873255df6c64f65d47e25c726c73d70605d

Instead of waiting for a set amount of time and clicks, it does a long poll until the element is, in fact, visible. 

As a side note, I shouldn't rely on `#gwt-uid-88` being consistent between different sessions. I replaced all `gwt*` selectors with more explicit ones.

**Comment by avantida** [comment]
Works like a charm!
Thanks a lot!
