### ISSUE TITLE
standalone solution

### ISSUE THREAD

**Issue by DanielRuf** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#10]
I would like to have some puppeteer based solution / script (NodeJS) or better something in Go(lang) which uses https://github.com/chromedp/chromedp so I can run it directly without configuring / installing the extension and run it in the background.

I could help with the Golang (and also NodeJS) approach as I have written some solutions with this in the past.

**Comment by noitcudni** [comment]
I have done some work with headless browsers myself, but I'm targeting an entirely different group of users. This headless/command line approach should probably belong to a separate project. I can be convinced otherwise.

**Comment by DanielRuf** [comment]
> This headless/command line approach should probably belong to a separate project.

Definitely and this is what I mean ;-)
