### ISSUE TITLE
Make button checks language agnostic

### ISSUE THREAD

**Issue by DanielRuf** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#13]
Currently the script only works when the browser is set to English.

For example `div:contains('Next')`.
But this breaks when we switch to German or any other language.

So far it seems every button has a unique and permanent ID.
We can use this (which is probably the best solution) or create a big list of strings and a switch-case for matching them accordingly per language. But this breaks faster and makes not much sense.

So we should check if we can use them:

request-removal (red): `#gwt-uid-2`
request removal (blue, in dialog): `#gwt-uid-62`
close (blue, in first dialog): `#gwt-uid-64`
cancel (request removal already made, in dialog): `#gwt-uid-70`
retry (request removal already made, in dialog): `#gwt-uid-72`
...

**Comment by noitcudni** [comment]
There's a reason why I am specifically only handling English. Those ids are transient, and they do change.

**Comment by DanielRuf** [comment]
> Those ids are transient, and they do change.

I have never seen that they change. Maybe I've missed something. But for me the IDs are the same every time I use this tool.
