### ISSUE TITLE
Does it work for Bing webmaster tools?

### ISSUE THREAD

**Issue by unusualblag** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#14]
Sorry for writing in the issues section. Didn't know where else to ask the question. Would this plugin work for Bing webmaster tools as well as I need to remove links in bulk on both platforms.

**Comment by noitcudni** [comment]
No, it doesn't. I can look into it. Can you send me to url to bing's removal tools?

**Comment by unusualblag** [comment]
I am not sure if you need to be logged in to Bing Webmasters. This link is the closest I can get you. https://www.bing.com/webmaster/help/bing-content-removal-tool-cb6c294d

**Comment by noitcudni** [comment]
I know this is not exactly what you were asking for, but I just finished working on the bulk url removal extension for bing webmaster tools.

https://github.com/noitcudni/bing-webmaster-tools-bulk-url-removal
