### ISSUE TITLE
Confirming I'm doing this right

### ISSUE THREAD

**Issue by rakullian** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#15]
Hello!

With the new google search console, I want to make sure that the URLs being recognized actually end up being removed. 

See the screenshot below... Currently I exported a list of error url's (we had been hacked and these URLs are indexed but not sitemapped and I can't get rid of them!). 

The URLs are being recognized but it gets up to 1001 URLs andt then nothing happens and I don't see them processing in the remove URL queue. 

Is there another step I'm missing or am I in the wrong place? 

![image](https://user-images.githubusercontent.com/72469499/95255912-18875580-07f0-11eb-989b-9456ae9bfc5a.png)

**Comment by noitcudni** [comment]
I believe you posted an issue in the wrong project, but whatever.
Go ahead and read https://github.com/noitcudni/google-search-console-bulk-url-removal#csv-format.

Chances are you have extra columns. 

You can also download the error csv to check out what it is that it's complaining about.

If you still couldn't get it to work, please send me your CSV file to lihster.developer@gmail.com.
