### ISSUE TITLE
I can't get the extension to work

### ISSUE THREAD

**Issue by josoy** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#16]
Hello,

I have many urls to remove.

I have installed the extension I upload a csv with the urls.

And it doesn't work.

I have tried many csv cases but it doesn't work.

I put a screenshot of the google crhome console to see if you can tell me the solution.

I need the extension to work I have

![Captura de pantalla 2020-10-18 a las 14 28 26](https://user-images.githubusercontent.com/29437999/96368827-36d54580-114e-11eb-9d5c-a297819d7f2e.jpg)

**Comment by josoy** [comment]
I ad ?hl=en to url and work!

**Comment by noitcudni** [comment]
Interesting. The extension should've redirected with ?hl=en.
