### ISSUE TITLE
I bought your extension, but it did not work

### ISSUE THREAD

**Issue by chenazmul** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#17]
I bought your extension, but this extension is useless. When I upload my CSV, it looks for verification for each link. 

My site: https://forprivacy.org/
Screenshot: https://prnt.sc/vhdqoo

Please let me know, What happen?

**Comment by noitcudni** [comment]
Please read
https://github.com/noitcudni/google-webmaster-tools-bulk-outdated-content-removal#csv-format

If the content is still live, you'll need to provide it with an outdated
word that was on the page as stated in the modal dialog.
Your csv file will need to have that word in a separate column.

Lih

**Comment by chenazmul** [comment]
can you please give me a example ? 

This is my csv: https://prnt.sc/vhqk63

Thanks

**Comment by noitcudni** [comment]
Let's say that you have https://your-domain.org/foo. The page is still
live, so google wants you to provide it with a word that was in the old
version but not in the current live version. Let's pretend that the word is
"hello".

In your csv file, you'll have the following entry.
https://your-domain.org/foo,hello

Once again I believe
https://github.com/noitcudni/google-webmaster-tools-bulk-outdated-content-removal#csv-format
spells
it out.

**Comment by chenazmul** [comment]
So, Is it completely removed from google by this way??

**Comment by chenazmul** [comment]
Same: https://prnt.sc/vhtji0

**Comment by chenazmul** [comment]
oh yes, it working :)

**Comment by chenazmul** [comment]
but why they denied?

**Comment by chenazmul** [comment]
https://prnt.sc/vhvas0

**Comment by noitcudni** [comment]
unsure. Do you own the site? What's your usecase?

**Comment by chenazmul** [comment]
Yes, i am the owner of this site. Recently, My website was hacked, I want to delete the spamming index page from google.

**Comment by noitcudni** [comment]
Got it. In that case, it may be better for you to use the bulk-url-removal
extension. I can refund you current purchase, and you can buy the
bulk-url-removal extension.

Also, you have an account on google search console, right?

https://chrome.google.com/webstore/detail/webmaster-tools-bulk-url/pmnpibilljafelnghknefahibdnfeece?hl=en-US

Lih

**Comment by chenazmul** [comment]
Yes, i have a acc on GSC. Ok refund me bro

**Comment by chenazmul** [comment]
I purchased, You refund me for the previous order

**Comment by chenazmul** [comment]
I did not find any upload option: https://prnt.sc/vidqms

**Comment by noitcudni** [comment]
That's a very old verson. Did you buy that? If so, when?

I'll need your purchase hash to refund you. Please send that to
lihster.developer@gmail.com

**Comment by chenazmul** [comment]
Sorry working... 

Where i find  purchase hash ?

**Comment by noitcudni** [comment]
Don't know to be honest, but my previous customers have no problems finding
it. I'm guessing somewhere in your account.
Did you purchase bulk removal long time ago? 'Cause that screenshot is
showing a really old version.

**Comment by chenazmul** [comment]
Its working bro, 

I told you Where i find purchase hash ?

**Comment by chenazmul** [comment]
???

**Comment by chenazmul** [comment]
Where my refund for bulk outdated content ? 

and why now its show this: https://prnt.sc/w0a7bp ??

Where I found my licence key ?

**Comment by noitcudni** [comment]
Send me an email directly at lihster.developer@gmail.com. I'll take care of
it.
