### ISSUE TITLE
license issue 

### ISSUE THREAD

**Issue by sumitrm** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#18]
I have purchased this extension on 23rd oct 2020,today suddenly it is asking me email and license code which i havent received on my email (sumitr.madgulkar@gmail.com),it was working since i purchased however started asking for license from today,can you please send me my license code on my registered email, thanks.

**Comment by noitcudni** [comment]
Yup, just replied to you directly via email. I'll email you your license
key shortly.
