### ISSUE TITLE
Issue With New Version

### ISSUE THREAD

**Issue by sumitrm** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#19]
Hi Lih,

Thanks for the new version,i tested it but it is crashing my browser and pc,also when csv contains already submitted url it terminates,no further action.I used csv with 500 urls and then 10 urls but same results.how can i revert to old version as its valid till 19th jan,till then you have time to rectify bugs in new version,thanks.

**Comment by noitcudni** [comment]
Try the instructions here: https://gist.github.com/juniorcesarabreu/115a4f5141cd1a841119c511c4c66d3f for reverting back to the older version.

Just wanted to double check. You purchased the extension, correct?
Can you send me both the csv files with 500 urls and 10 urls to my email at lihster.developer@gmail.com

**Comment by sumitrm** [comment]
Yes,i have purchased extention and contacted u previously regarding license
issue,where u provided me new key 😀

**Comment by sumitrm** [comment]
Here are some sample csv file i am using

**Comment by noitcudni** [comment]
Yeah, just realized that. I've never tried the method of reverting to an older extension in the link I posted earlier. If that doesn't work, let me know.

**Comment by noitcudni** [comment]
You have to email me the csv files. lihster.developer@gmail.com

**Comment by noitcudni** [comment]
Just got it. Thanks.

**Comment by sumitrm** [comment]
I had old backup which i uploaded just now ,its working on old page,it will
help till u rectify :-)

**Comment by noitcudni** [comment]
I'm not able to get my browser nor my computer to crash. However, I did notice that there are two cases that I wasn't aware of.
1. Oops, something went wrong, please try again later.
2. You've already submitted this URL.

The extension previously got stuck when encountering the above error messages.
