### ISSUE TITLE
example of working upload file

### ISSUE THREAD

**Issue by GitTraffic** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#2]
Would it be possible for you to provide an example of a working upload file listing URLs?

**Comment by noitcudni** [comment]
Yup, it's just a CSV file with one column
```
http://somedomain.com/1
http://somedomain.com/2
http://somedomain.com/3
```
That's it.

**Comment by Bhoomil12** [comment]
pls send link of example csv file to download

**Comment by noitcudni** [comment]
Sorry, I don't understand where the confusion lies. It's literally just a file with a single column of URLs. See my previous comment.
