### ISSUE TITLE
Extension stops and crashes the tab

### ISSUE THREAD

**Issue by atazok** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#20]
Hello,
The extension starts to submit urls and when it submits around 40 urls it becomes really slow, while at around 70 urls it finally stops. The tab reload is also very slow and sometimes it becomes unresponsive. I tried to view/clear cache, but nothing seems to happen. Every time I upload new csv file only with the urls left for submission to avoid errors. The csv is formatted following your example.

To keep it working I have a tab always open, since I looks like it stops if you switch to another tab. If it's working in the background I can't really tell.

I would appreciate any help, I'm no coder, thanks.

**Comment by noitcudni** [comment]
Did you purchase the extension or did you compile it yourself? The 2 versions have diverged a bit. 

It has been always the case that the tab needs to stay open and active.

**Comment by atazok** [comment]
Hey, and thanks for the reply. I have purchased it and installed as a normal extension.

**Comment by noitcudni** [comment]
What's the version number of the extension?
Another customer brought up the slowness to me awhile back. Apparently, the new dashboard (for reasons unbeknownst to me) fires off one additional ajax call per table entry just to populate the tooltip. The extension should intercept that http ajax call and prevent it from happening. 

Can you do me a favor? If you mouse over the question mark tooltip, does the tooltip show up? It shouldn't.

It could be another issue that's causing the slow down. Do you have another 40 - 70 extra urls lying around? I'd like to reproduce the issue on my end.

**Comment by noitcudni** [comment]
Oh, send me your csv file with the extra 40-70 urls to lihster.developer@gmail.com

**Comment by atazok** [comment]
I'm using version 1.0.4.  When I mouse over the "submit csv" button a tooltip message shows up. See it [here.](https://snipboard.io/HPQETm.jpg)
I've sent you 100 url to test it to your email.

**Comment by noitcudni** [comment]
Interesting. Could be the case that they changed their http call. Will take
a look tomorrow night

On Tue, Jan 12, 2021 at 10:38 PM atazok <notifications@github.com> wrote:

> I'm using version 1.0.4. When I mouse over the "submit csv" button
>
a tooltip message shows up. See it here. <https://snipboard.io/HPQETm.jpg>

**Comment by noitcudni** [comment]
No I meant the tooltip on the entry on the page. Not the extension pop up.
Anyway I’ll take a look
