### ISSUE TITLE
Cancel my subscription

### ISSUE THREAD

**Issue by robbad2021** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#21]
Hello Lih, I would like to install this removal system, but it is not clear to me how in the future I can ask you to cancel the service.

As soon as I select subscribers, the page with the payment details opens, but you do not explain how I can unsubscribe and how long the minimum subscription lasts.

Thanks
Roberto

**Comment by noitcudni** [comment]
Sorry, I just came across this. There's a link that will bring you to your membership management page. From there, you can cancel. Let me know if you need help. I can also cancel it for you, but I'll need your email address that you used when making the purchase.

**Comment by noitcudni** [comment]
To answer your question. The minimum duration is a month. You can cancel at anytime.
