### ISSUE TITLE
Purchase, uploaded correct csv, but nothing happens

### ISSUE THREAD

**Issue by dreamflasher** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#22]
I am on the English page: https://search.google.com/search-console/remove-outdated-content?hl=en
I uploaded a correctly formatted csv, but the script isn't doing anything.

**Comment by noitcudni** [comment]
A recent chrome version disallowed triggering a click event from background or popup. Luckily, once I migrated to manifest 3, the problem went away.

I wonder if the latest chrome version imposes the same restriction. I'm looking into this now.

Which version of chrome are you using?

**Comment by noitcudni** [comment]
Just upgraded my chrome to the latest version, and it worked fine for me.

Are you sure that you purchased the correct extension? There are 2. One is for outdated content removal (you bought this one), while the other works inside Google Search Console.

**Comment by dreamflasher** [comment]
As you seem to know which one I purchased, I'd assume you know that it's the correct one? I installed the extension and purchased what the extension told me to do.

**Comment by noitcudni** [comment]
Which version of chrome are you using? Can you email me your csv file?

**Comment by noitcudni** [comment]
Silly Question. Did you try refreshing the page?

**Comment by dreamflasher** [comment]
Several times, including restarting the browser.
I use Chromium Version 88.0.4324.150
I'll send you the file.

**Comment by noitcudni** [comment]
Chromium? As in the open source chrome browser? Can you try running it on
the latest Google Chrome Browser?

**Comment by dreamflasher** [comment]
Chromium and Chrome are feature identical.

**Comment by noitcudni** [comment]
In any case, can you try upgrading your chromium browser? Mine is
97.0.4692.99

**Comment by noitcudni** [comment]
![image](https://user-images.githubusercontent.com/78951/151929662-35a91217-f22d-44e2-afa3-a8b4c482d2b9.png)

I downloaded the exact version of chromium. I proceeded to install my latest build of my extension. Apparently, you are running an older chromium version that doesn't support manifest v3.

**Comment by dreamflasher** [comment]
The reason was my outdated chrome, thank you for your help, now it works like a charm!
