### ISSUE TITLE
Only first url is ok

### ISSUE THREAD

**Issue by druplash** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#4]
Hi, the bulk upload tool is not working correct. Only the first url (line) in CSV is read from your tool. All other url (700 and more) are not uploaded. Please can you help me? Thanks!

**Comment by noitcudni** [comment]
Can you send me your csv file?

**Comment by dsignid** [comment]
Hi,
I also found the same problem, I can't upload with a large number of links.
I have also sent the CSV file to your email (lihster.developer@gmail.com) , please help me.

Thank you very much.

**Comment by noitcudni** [comment]
@dsignid I just checked my email. I don't believe that I got your email.
