### ISSUE TITLE
Upload Problem

### ISSUE THREAD

**Issue by Prusaseo** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#6]
Hi my friend, i download your file and opened it to the desktop. And then go to the extension, activate the developer mode and then load unpacked extension. But my files not seen for the uploads.
when i opened the downloaded file i see all files... But when i clikc the load files are not seen...
Could u help me...
![bulk 0](https://user-images.githubusercontent.com/60224571/72992688-4153f000-3e05-11ea-8236-b50f40748752.jpg)
![bulk1](https://user-images.githubusercontent.com/60224571/72992689-4153f000-3e05-11ea-93f7-1663cce70e13.jpg)
![bulk2](https://user-images.githubusercontent.com/60224571/72992692-41ec8680-3e05-11ea-968a-82684ed8b282.jpg)
![bulk 4](https://user-images.githubusercontent.com/60224571/72992749-56308380-3e05-11ea-9646-f14d013d60a6.jpg)

**Comment by noitcudni** [comment]
hmm..I don't use windows. You can try `git clone` the repo?

**Comment by DanielRuf** [comment]
The content of the downloaded zip file should look like this:

<img width="276" alt="Bildschirmfoto 2020-04-19 um 14 05 48" src="https://user-images.githubusercontent.com/827205/79687352-fbad9480-8246-11ea-98fc-83d6d0e790ce.png">


What you show us on the screenshots is this project: https://github.com/noitcudni/google-search-console-bulk-url-removal

The readme explains the needed steps. I think we should move this issue to there.
