### ISSUE TITLE
It's not automatic, what happened!

### ISSUE THREAD

**Issue by dersemdein** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#7]
A few hours ago I bought the tool, before it was free, installed and the removal was automatic. Now I installed it and only load one of the whole list (there are 564) and it is not automatic, please indicate what to do because I bought it to speed up processes not to waste time. Please write info@clipcd.com
![url](https://user-images.githubusercontent.com/12383673/73686209-8b569480-4695-11ea-9030-d3dbe03ecf16.JPG)

**Comment by noitcudni** [comment]
Please send me your csv file.

**Comment by dersemdein** [comment]
Ok attached the file, but in the future it doesn't have to be like that, in its free version it was more efficient.


[CLIPCD FIRMA CORREO_Mesa de trabajo 1]

De: Lih <notifications@github.com>
Enviado el: lunes, 3 de febrero de 2020 15:48
Para: noitcudni/google-webmaster-tools-bulk-outdated-content-removal <google-webmaster-tools-bulk-outdated-content-removal@noreply.github.com>
CC: dersemdein <dersemdein@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [noitcudni/google-webmaster-tools-bulk-outdated-content-removal] It's not automatic, what happened! (#7)

Please send me your csv file.

**Comment by noitcudni** [comment]
Ah, I see that selected domain doesn't match the domain name specified in
your CSV file.
Note: this is why are are seeing entries like
http://www.zanminepure.comhttp://www.mal...
<---this is an erroneous url.

**Comment by noitcudni** [comment]
The "free" version and the version on the webstore are meant to be the
same. FYI

**Comment by dersemdein** [comment]
Apparently not, before I didn't have to send the CSV to any mail, now I do.

[CLIPCD FIRMA CORREO_Mesa de trabajo 1]

De: Lih <notifications@github.com>
Enviado el: lunes, 3 de febrero de 2020 15:56
Para: noitcudni/google-webmaster-tools-bulk-outdated-content-removal <google-webmaster-tools-bulk-outdated-content-removal@noreply.github.com>
CC: dersemdein <dersemdein@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [noitcudni/google-webmaster-tools-bulk-outdated-content-removal] It's not automatic, what happened! (#7)

The "free" version and the version on the webstore are meant to be the
same. FYI

On Mon, Feb 3, 2020 at 12:54 PM dersemdein <notifications@github.com<mailto:notifications@github.com>> wrote:

>
> Ok attached the file, but in the future it doesn't have to be like that,
> in its free version it was more efficient.
>
>
> [CLIPCD FIRMA CORREO_Mesa de trabajo 1]
>
> De: Lih <notifications@github.com<mailto:notifications@github.com>>
> Enviado el: lunes, 3 de febrero de 2020 15:48
> Para: noitcudni/google-webmaster-tools-bulk-outdated-content-removal <
> google-webmaster-tools-bulk-outdated-content-removal@noreply.github.com<mailto:google-webmaster-tools-bulk-outdated-content-removal@noreply.github.com>>
> CC: dersemdein <dersemdein@hotmail.com<mailto:dersemdein@hotmail.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
>
> Asunto: Re:
> [noitcudni/google-webmaster-tools-bulk-outdated-content-removal] It's not
> automatic, what happened! (#7)
>
> Please send me your csv file.
>
> On Mon, Feb 3, 2020 at 11:57 AM dersemdein <notifications@github.com

**Comment by noitcudni** [comment]
> Ah, I see that selected domain doesn't match the domain name specified in your CSV file. Note: this is why are are seeing entries like http://www.zanminepure.comhttp://www.mal... <---this is an erroneous url.

^^^ Did you read this?

**Comment by dersemdein** [comment]
If I have read it, to access to delete the domain I only need to upload the txt or csv file, the same as the one I sent. I have no idea why the tool puts a wrong domain url before it.

[CLIPCD FIRMA CORREO_Mesa de trabajo 1]

De: Lih <notifications@github.com>
Enviado el: lunes, 3 de febrero de 2020 16:03
Para: noitcudni/google-webmaster-tools-bulk-outdated-content-removal <google-webmaster-tools-bulk-outdated-content-removal@noreply.github.com>
CC: dersemdein <dersemdein@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [noitcudni/google-webmaster-tools-bulk-outdated-content-removal] It's not automatic, what happened! (#7)


Ah, I see that selected domain doesn't match the domain name specified in your CSV file. Note: this is why are are seeing entries like http://www.zanminepure.comhttp://www.mal<http://www.zanminepure.comhttp:/www.mal>... <---this is an erroneous url.

^^^ Did you read this?

**Comment by noitcudni** [comment]
First of all, this is not the right extension for removing outdated url. The url is https://www.google.com/webmasters/tools/removals.

But I am fairly certain that you are talking about the url removal tool (the legacy version).
In any case, can you take a more comprehensive screen shot which includes the dropdown on the upper right hand corner?

**Comment by dersemdein** [comment]
[cid:image003.jpg@01D5DAAD.AA49AC50]

[CLIPCD FIRMA CORREO_Mesa de trabajo 1]

De: Lih <notifications@github.com>
Enviado el: lunes, 3 de febrero de 2020 16:15
Para: noitcudni/google-webmaster-tools-bulk-outdated-content-removal <google-webmaster-tools-bulk-outdated-content-removal@noreply.github.com>
CC: dersemdein <dersemdein@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [noitcudni/google-webmaster-tools-bulk-outdated-content-removal] It's not automatic, what happened! (#7)


First of all, this is not the right extension for removing outdated url. The url is https://www.google.com/webmasters/tools/removals.

But I am fairly certain that you are talking about the url removal tool (the legacy version).
In any case, can you take a more comprehensive screen shot which includes the dropdown on the upper right hand corner?

**Comment by noitcudni** [comment]
I can't see it. It's showing up as markdown.
![image](https://user-images.githubusercontent.com/78951/73691846-044eef80-4688-11ea-8ced-a0c677ff210d.png)
Take a look at my screenshot. Pay close attention to the dropdown on the upper right hand corner. Whatever's selected there has to match the domain names in your csv file. Otherwise, google's url removal app (not me) will simply append whatever is in your csv file after the selected domain name.

**Comment by dersemdein** [comment]
Ok archive!

[cid:image001.jpg@01D5DAAE.8FDA9810]




De: Lih <notifications@github.com>
Enviado el: lunes, 3 de febrero de 2020 16:15
Para: noitcudni/google-webmaster-tools-bulk-outdated-content-removal <google-webmaster-tools-bulk-outdated-content-removal@noreply.github.com>
CC: dersemdein <dersemdein@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [noitcudni/google-webmaster-tools-bulk-outdated-content-removal] It's not automatic, what happened! (#7)


First of all, this is not the right extension for removing outdated url. The url is https://www.google.com/webmasters/tools/removals.

But I am fairly certain that you are talking about the url removal tool (the legacy version).
In any case, can you take a more comprehensive screen shot which includes the dropdown on the upper right hand corner?

**Comment by noitcudni** [comment]
What did you mean by "Ok archive!"?

**Comment by dersemdein** [comment]
the links you see I've included with the tool but one by one, it's not automatic.

[CLIPCD FIRMA CORREO_Mesa de trabajo 1]

De: Lih <notifications@github.com>
Enviado el: lunes, 3 de febrero de 2020 16:22
Para: noitcudni/google-webmaster-tools-bulk-outdated-content-removal <google-webmaster-tools-bulk-outdated-content-removal@noreply.github.com>
CC: dersemdein <dersemdein@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [noitcudni/google-webmaster-tools-bulk-outdated-content-removal] It's not automatic, what happened! (#7)


I can't see it. It's showing up as markdown.
[image]<https://user-images.githubusercontent.com/78951/73691846-044eef80-4688-11ea-8ced-a0c677ff210d.png>
Take a look at my screenshot. Pay close attention to the dropdown on the upper right hand corner. Whatever's selected there has to match the domain names in your csv file. Otherwise, google's url removal app (not me) will simply append whatever is in your csv file after the selected domain name.

**Comment by dersemdein** [comment]
…picture correctly attached…

[CLIPCD FIRMA CORREO_Mesa de trabajo 1]

De: Lih <notifications@github.com>
Enviado el: lunes, 3 de febrero de 2020 16:29
Para: noitcudni/google-webmaster-tools-bulk-outdated-content-removal <google-webmaster-tools-bulk-outdated-content-removal@noreply.github.com>
CC: dersemdein <dersemdein@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [noitcudni/google-webmaster-tools-bulk-outdated-content-removal] It's not automatic, what happened! (#7)


What did you mean by "Ok archive!"?

**Comment by noitcudni** [comment]
I am not seeing the photo. You can send it directly to lihster.developer@gmail.com.

**Comment by noitcudni** [comment]
> I can't see it. It's showing up as markdown.
> ![image](https://user-images.githubusercontent.com/78951/73691846-044eef80-4688-11ea-8ced-a0c677ff210d.png)
> Take a look at my screenshot. Pay close attention to the dropdown on the upper right hand corner. Whatever's selected there has to match the domain names in your csv file. Otherwise, google's url removal app (not me) will simply append whatever is in your csv file after the selected domain name.

**Comment by noitcudni** [comment]
> I can't see it. It's showing up as markdown.
> ![image](https://user-images.githubusercontent.com/78951/73691846-044eef80-4688-11ea-8ced-a0c677ff210d.png)
> Take a look at my screenshot. Pay close attention to the dropdown on the upper right hand corner. Whatever's selected there has to match the domain names in your csv file. Otherwise, google's url removal app (not me) will simply append whatever is in your csv file after the selected domain name.

^^ What does your drop down to the right of the blue button say?

**Comment by noitcudni** [comment]
![image](https://user-images.githubusercontent.com/78951/73706343-1b540880-46ad-11ea-86d2-87f3e06d9daf.png)

Exactly what I suspected. The urls in your csv files have domains that don't match the domain as highlighted in the upper right hand corner. Do you own, for example, jdcontractingservices.com.au and megaindex.ru?

**Comment by dersemdein** [comment]
Hello, let me know if you have a solution, the tool has to do the process in automatic. Why do you put the domain link first if you didn't do it before?... The tool does not run automatically

[CLIPCD FIRMA CORREO_Mesa de trabajo 1]

De: Lih <notifications@github.com>
Enviado el: lunes, 3 de febrero de 2020 20:48
Para: noitcudni/google-webmaster-tools-bulk-outdated-content-removal <google-webmaster-tools-bulk-outdated-content-removal@noreply.github.com>
CC: dersemdein <dersemdein@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [noitcudni/google-webmaster-tools-bulk-outdated-content-removal] It's not automatic, what happened! (#7)


[image]<https://user-images.githubusercontent.com/78951/73706343-1b540880-46ad-11ea-86d2-87f3e06d9daf.png>

Exactly what I suspected. The urls in your csv files have domains that don't match the domain as highlighted in the upper right hand corner. Do you own, for example, jdcontractingservices.com.au and megaindex.ru?
