### ISSUE TITLE
Big Problem

### ISSUE THREAD

**Issue by DrinkoLee** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#8]
Hello friend, was there any update? because now it doesn't do the automatic way, we have to confirm the deletion link by link.

**Comment by noitcudni** [comment]
What version are you using?

**Comment by DrinkoLee** [comment]
0.1, help me

**Comment by noitcudni** [comment]
Just wanted to make sure you are referring to the correct extension. You are NOT talking about https://github.com/noitcudni/google-search-console-bulk-url-removal, are you?

**Comment by DrinkoLee** [comment]
Oh my friend, I was talking about this

https://github.com/noitcudni/google-webmaster-tools-bulk-outdated-content-removal


but I just saw that you sent me another link, but I can NEVER install this link that you sent now.  :/

**Comment by DanielRuf** [comment]
> but I just saw that you sent me another link, but I can NEVER install this link that you sent now. :/

Please provide the exact steps that you tried so we can reproduce this.
