### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by michelelang** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#9]
Did this extension stop working?

**Comment by noitcudni** [comment]
It should still work. I'm in the process of rewriting it. Can you give more details as to how it's not working for you?

**Comment by michelelang** [comment]
The extension is not activating - I deleted and re-downloaded, and it never activates to have the option to add a file.

**Comment by noitcudni** [comment]
Would you please take a screenshot of it?

**Comment by DanielRuf** [comment]
> The extension is not activating - I deleted and re-downloaded, and it never activates to have the option to add a file.

Please check if your browser has set English as first language.
If we would use something like puppeteer this would not happen as we can can control the language of the Chromium / Chrome instance and can ensure that it always works. Also see #10 (could be also used with some Docker setup - see https://github.com/DanielRuf/website-checks/blob/master/Dockerfile for some example setup).
